version: '3'

services:
  bitcoin:
    image: blockstream/bitcoind:27.2
    platform: linux/amd64
    command:
      [
        "bitcoind",
        "-printtoconsole",
        "-regtest=1",
        "-rpcallowip=0.0.0.0/0",
        "-rpcbind=0.0.0.0",
        "-rpcuser=user",
        "-rpcpassword=pass",
        "-fallbackfee=0.00001",
        "-rest"
      ]
    ports:
      - "18443:18443"  # Regtest REST and RPC port
      - "18444:18444"  # Regtest P2P port
    networks:
      - bitcoin-electrs
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-regtest", "-rpcuser=user", "-rpcpassword=pass", "getblockchaininfo"]
      interval: 5s
      timeout: 10s
      retries: 5

  electrs:
    image: mempool/electrs:v3.2.0
    platform: linux/amd64
    depends_on:
      bitcoin:
        condition: service_healthy
    command:
      [
        "-vvvv",
        "--timestamp",
        "--jsonrpc-import",
        "--cookie=user:pass",
        "--network=regtest",
        "--daemon-rpc-addr=bitcoin:18443",
        "--http-addr=0.0.0.0:3002"
      ]
    ports:
      - "3002:3002"
    networks:
      - bitcoin-electrs

networks:
  bitcoin-electrs:
    driver: bridge
