name: Security Audit
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  audit:
    timeout-minutes: 60
    permissions:
      issues: write
      checks: write
    strategy:
      matrix:
        platform: [
          self-hosted,
          macos-latest,
          windows-latest,
          ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
      - name: Run security audit
        uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
