name: Build Python Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v4

      - name: Generate Python bindings
        run: bash ./scripts/uniffi_bindgen_generate_python.sh

      - name: Build wheels
        uses: pypa/cibuildwheel@v1.12.0
        env:
          CIBW_ARCHS_MACOS: "x86_64 arm64 universal2"
          CIBW_ARCHS_LINUX: "auto aarch64"
          CIBW_BUILD_VERBOSITY: 1
        with:
          package-dir: ./bindings/python

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
