name: CI Checks - CLN Integration Tests

on: [push, pull_request]

jobs:
  check-cln:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create temporary directory for CLN data
        id: create-temp-dir
        run: echo "CLN_DATA_DIR=$(mktemp -d)" >> $GITHUB_ENV

      - name: Start bitcoind, electrs, and lightningd
        run: docker compose -f docker-compose-cln.yml up -d

      - name: Run CLN integration tests
        run: |
          CLN_SOCK=$CLN_DATA_DIR/lightning-rpc RUSTFLAGS="--cfg cln_test" cargo test --test integration_tests_cln
